### PR TITLE
Singularized Batches -> Batch

### PR DESCRIPTION
**Pull request by ananay**

### CODE REVIEW

**Comment by ananay** [comment]
@abhishek97

**Comment by abhishek97** [comment]
We would like to keep this as batches only. Thank you.

**Comment by ananay** [comment]
Sure!
Do I still get points for doing the task, though?

**Comment by championswimmer** [comment]
@abhishek97 
`1 batch starting from...` 
sounds better than
`1 batches starting from ...`

**Comment by ananay** [comment]
Fixing conflicts and pushing again

**Comment by championswimmer** [comment]
Oh this is the wrong place to do this. @ananay 

There was an earlier place in ui where there was text

**1 Batches starting from**

I made the issue to resolve that. 

This place should remain batches, otherwise the language seems odd "Choose from Available Batch" vs ""Choose from Available Batches" (2nd is better)

**Comment by ananay** [comment]
Got it.

**Pull request closed without merging**
