### PR TITLE
Added skeleton cards

### PR DESCRIPTION
**Pull request by hereisnaman**
fixes: https://github.com/coding-blocks/codingblocks.online.projectx/issues/29
Have opened another PR for css changes at motley https://github.com/coding-blocks/motley/pull/138 . This includes the required html changes.

screen shot 2018-05-14 at 11 46 26 pm

### CODE REVIEW

**Comment by aayusharora** [comment]
This looks super awesome @hereisnaman 
Can you please check if we can have animations for these skeleton inner elements ?

**Comment by hereisnaman** [comment]
@aayusharora Thanks, as I requested earlier, if you can provide me with the svg having white bg but transparent placeholders, the animations can be done. Currently the placeholders are opaque but transparent bg.

**Comment by championswimmer** [comment]
WOOO! These look awesome

**Comment by hereisnaman** [comment]
@championswimmer for more OOOOOs please get me the requested svg, will do some animations.

**Comment by abhishek97** [comment]
@hereisnaman I'll get the svg's from our designer and update the issue.

**Comment by abhishek97** [comment]
@hereisnaman See if this helps you https://www.dropbox.com/s/sw9lmnmfanafgvz/blankcard.svg?dl=0

Also the build is failing for this PR.

**Comment by witty123** [comment]
@hereisnaman https://www.dropbox.com/s/t421f1shnmfwka2/blankcard.svg?dl=0
SVG with white background

**Comment by hereisnaman** [comment]
Oh, so now when the whole img is opaque, you expect the animations to happen!

**Comment by witty123** [comment]
@hereisnaman can you please check why build is failing ?

**Comment by witty123** [comment]
@hereisnaman this is to be done using pure css. The whole philosophy of having skeleton cards is to reduce the interaction time of the user. If you are implementing it with svg then there's another overhead. I didn't read the whole conversation but what I thought you needed were the designs of the skeleton card. 
Here's a demo that you can follow for creating them with pure css. https://codepen.io/oslego/pen/XdvWmd

**Comment by hereisnaman** [comment]
@witty123 there is obviously no problem in creating using pure css but just one. You can't have border radius. That's the only issue. Because one can't mask out the background (cut transparent portions from the bg). With css the approach is that you color filled (white) divs around the placeholder area.

So if you are okay with no border radius of the placeholders, I can do it. Otherwise will need svg. Though It really won't be an overhead If made inline.

**Comment by witty123** [comment]
I think we can live with SVGs for now since you have already spent so much time on it. Can you share your exact requirements ?

**Comment by hereisnaman** [comment]
See the thing is If you need animations and border radius for the placeholders then can't do it with only css. with border-radius 0 I can do that with css same as you shared in a codepen, there also you won't find border-radiius for the placeholders having animations. Or otherwise I just need a svg, in which the bg is white and the placeholders are transparent. Like masking out the bg at placeholder places. 

Then I can simply put a bg slide transition on the parent div of the svg for the animations.

Another way is I just do bg animations for the placeholder divs. But in that case due to difference in various div's widths and position, the animations in the placeholders won't be in sync.

**Comment by witty123** [comment]
Cool, I'll update you with the new svg shortly.

**Comment by witty123** [comment]
https://www.dropbox.com/s/t421f1shnmfwka2/blankcard.svg?dl=0

@hereisnaman will this work for you ?

**Comment by witty123** [comment]
@hereisnaman any updates ? If you can't work any further on this then can you fix the build so that we can merge this.

**Comment by witty123** [comment]
Closing because of inactivity.

**Pull request closed without merging**
