### PR TITLE
fixed search width Issue 35

### PR DESCRIPTION
**Pull request by hereisnaman**
fixes: https://github.com/coding-blocks/codingblocks.online.projectx/issues/35

I have worked on home-container padding and search box width, made it 50%, center aligned, min 290px for w<768px. SS : 
screen shot 2018-05-14 at 11 04 33 pm

Also it fixes: https://github.com/coding-blocks/codingblocks.online.projectx/issues/30

### CODE REVIEW

**Comment by abhishek97** [comment]
This looks bad for both iPad and iPad-pro and not-centered for everything between 768px and 1366px. Also, it will be better to have a wider search box for tablets.

**Comment by abhishek97** [comment]
The image looks too big, wrap it inside a `col-6` maybe?. We have a custom breakpoint to show carousel cards at `min-width: 1334px`, you'll need to handle the image position for this via media-query as this is not a bootstrap breakpoint.

**Comment by hereisnaman** [comment]
Yeah I am using 1334 only, have made img 50% for 767 < w < 1335. SS: 
screen shot 2018-05-15 at 12 24 49 pm

**Comment by abhishek97** [comment]
This project uses motley(https://github.com/coding-blocks/motley/) as css framework. We don't accept css changes here. Please consider a PR to motley instead.

**Pull request closed without merging**
