### PR TITLE
Closes notification box when clicked outside it.

### LINKED ISSUE #132: Make Notification Box Close when clicked outside it
screen shot 2018-06-20 at 1 35 54 pm

Currently only way to close it is clicked the bell icon again.

### PR DESCRIPTION
**Pull request by Rishabh570**
Fixes #132 .

Pinging @abhishek97

### CODE REVIEW

**Comment by abhishek97** [comment]
@Rishabh570 Please take look at the diff here, i think it is missing some changes.

**Comment by Rishabh570** [comment]
@abhishek97 Its working now

**Comment by Rishabh570** [comment]
@abhishek97 I need little help in logging in to `codingblocks.online.projectx` on localhost...After login process I get an auth_code in URL, like this:
`http://localhost:4200/?code=sodsjflssdfsfsd2fs0`
What next!?, how to get Logged In in development on localhost?

**Comment by abhishek97** [comment]
@Rishabh570 Yes, we are writing up docs for it soon. 
Btw, This PR although merged, has some issues. Like when user clicks inside the notification-box, it closes the navigation box so that click event is not triggered for the element inside notification box.

**Comment by Rishabh570** [comment]
@abhishek97 Sorry, I was afk...Thanks for completion.
It would be nice to have docs for it, but I am currently working on this repo that's why I asked this. 
Can you give a quick tip of next step, whenever you find time... 👍

**Pull request merged**
