### PR TITLE
conditional script of jivochat

### PR DESCRIPTION
**Pull request by architkshk**
@abhishek97 pls review. #259

### CODE REVIEW

**Comment by architkshk** [comment]
@abhishek97 will this do it??

**Comment by architkshk** [comment]
screenshot from 2018-08-14 00-00-57
screenshot from 2018-08-14 00-01-12
@abhishek97

**Comment by abhishek97** [comment]
Yes, it will. However, may I suggest a smaller check. Most of the times such a "thorough" check against UA is an overkill.

**Comment by architkshk** [comment]
@abhishek97 Done the suggested changes.

**Comment by championswimmer** [comment]
@abhishek97 @architkshk 
did you check this comment - 
https://github.com/coding-blocks/codingblocks.online.projectx/issues/259#issuecomment-412630010 

does it always work ? because it needs to make sure onload has happened. 
if this is working without any issues, then fine, but please do make sure!

**Comment by witty123** [comment]
@championswimmer is right. This won't work in most of the cases. Also User agent sniffing can't be trusted alone, these strings keep on changing with time. Why not just check the screen width of the device and get done with it ? Won't have to add another device in the list you already have.

**Pull request merged**
