### PR TITLE
buy button and free trial

### LINKED ISSUE #243: Add free trial info and buy now link in course dashboard
screen shot 2018-08-11 at 6 07 54 pm
If the course access that the user currently has is a free trial then show that data and ask him to purchase full course as well by showing him the buy now button.
You'll have to come up with designs and PR in motley as well.

### PR DESCRIPTION
**Pull request by architkshk**
fixes #243 @witty123 @abhishek97 
screenshot from 2018-08-12 00-59-38

### CODE REVIEW

**Comment by witty123** [comment]
Can we have different designs for resume learning and buy now button ? Maybe make the primary CTA (buy now) filled and secondary CTA (resume learning) dashed.

**Comment by architkshk** [comment]
@witty123 Done!

**Comment by architkshk** [comment]
Button solid for resume learning if premium otherwise button dashed

**Comment by witty123** [comment]
screen shot 2018-08-13 at 1 09 13 pm

**Comment by architkshk** [comment]
i'll make pr in motley.

**Comment by witty123** [comment]
also check in case of mobile screen width

**Comment by architkshk** [comment]
@witty123  Done !!! https://github.com/coding-blocks/motley/pull/269

**Pull request merged**
