### PR TITLE
deprecated jquery removed from project

### LINKED ISSUE #419: Deprecate Jquery
Jquery was included by default in Ember.js. Though it has served its purpose well, current state of ember and browsers no longer needs Jquery. Ember also has officially [deprecated Jquery](https://github.com/emberjs/rfcs/blob/master/text/0386-remove-jquery.md), we also wish to do the same.

Task: Remove all usages of jQuery throughout the project. One way to get started is to remove `@ember/jquery` package from package.json and re-rerun `yarn install` and check for errors due to absence of Jquery and fix them with suitable Vanilla JS / Ember code.

### PR DESCRIPTION
**Pull request by farhan787**
fixes #419

### CODE REVIEW

**Comment by farhan787** [comment]
@abhishek97 please review it and if there are things to change then tell me, I'll do it.

**Comment by abhishek97** [comment]
You must tell ember, you opting out of jquery. Run `ember feature:disable jquery-integration`
then run `yarn install` to sync deps. 

You will be greeted with the console errors. One of those is due to `ember-ajax`, that we need to drop and replace with `ember-fetch`. This might not be trivial so read up on how they are used.
We must drop `ember-ajax` for `ember-fetch` as the former doesn't work without Jquery.

**Comment by farhan787** [comment]
Ok. I'm doing it.

**Comment by farhan787** [comment]
@abhishek97 I messed up things in this branch, would you mind continuing with [this PR](https://github.com/coding-blocks/codingblocks.online.projectx/pull/442). Now, `jquery` is totally deprecated and `ember-ajax` is also replaced with `ember-fetch`.

**Pull request closed without merging**
