### PR TITLE
Pointy arrow symbol for drop down

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Resolves issue 11
Used arrows for dropdown, fixed the arrow position on the selector box.

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 same here, I have already made a PR to motley for the CSS changes. Shall I undo them here?

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 @witty123 updates?

**Comment by VibhorCodecianGupta** [comment]
@witty123 @abhishek97 updated PR, please have a look.

All the CSS changes for these PRs (subparts for #193) have already been made to Motley

**Comment by abhishek97** [comment]
@VibhorCodecianGupta Link to merged/proposed motley PR?

**Pull request merged**
