### PR TITLE
Remove <div> wrapper from <button>

### LINKED ISSUE #413: Remove <div> wrapper from <button>
There are two primitive button class types used in our platform:-
`.button-solid` & `.button-dashed`

In some files, `<button>` elements are wrapped inside `<div>`. Remove the `<div>` wrapper and apply all the classes and actions to `<button>` respectively. 

For instance, you will find in `/app/pods/components/otp-enroll/template.hbs::line22`
```
<div class="button-solid" {{action 'handleClick'}}>
  <button>{{buttonText}}</button>
</div>
```
After refactoring it should look like
`<button class="button-solid" {{action 'handleClick'}}>{{buttonText}}</button>`

### PR DESCRIPTION
**Pull request by samagragupta**
fixes #413

### CODE REVIEW

**Comment by samagragupta** [comment]
@vdvibhu20 Please review.

**Comment by samagragupta** [comment]
@abhishek97 please review.

**Comment by vdvibhu20** [comment]
@samagragupta There are still many files which are not refactored.

**Comment by samagragupta** [comment]
@vdvibhu20 Can you please name few of them. I could not found them.

**Comment by vdvibhu20** [comment]
one of them:-
`app/pods/attempt/content/quiz/attempt/done/template.hbs:`

**Comment by samagragupta** [comment]
@vdvibhu20 There is no `<button>` tag

**Pull request closed without merging**
