### PR TITLE
[SOLVED] contents are clickable in premium runAttempt

### PR DESCRIPTION
**Pull request by Dhroov7**
@abhishek97 Please review.

### CODE REVIEW

**Comment by Dhroov7** [comment]
@abhishek97 Done! Please check.

**Comment by abhishek97** [comment]
@Dhroov7 If the course has no free content, we're stuck on the loading screen (a free trial user visiting a premium content link -> should load up a "Locked" screen)

**Comment by Dhroov7** [comment]
screenshot 2019-02-04 at 8 18 51 pm

@abhishek97 Please review.

**Comment by abhishek97** [comment]
Closed in favor of #329

**Pull request closed without merging**
