### PR TITLE
Enable Scrolling to Top

### LINKED ISSUE #418: We need to scroll to the top of the page, when showing pages
By Default, the scroll position is preserved while transitioning routes. However, at times this isn't the desired behaviour. 
We need to scroll to top for the following pages:

- [ ] Home
- [ ] All Courses
- [ ] My Courses
- [ ] Course Timeline (Course Overview)
- [ ] Course/:id

### How ?
Use [ember-router-scroll](https://github.com/dollarshaveclub/ember-router-scroll) plugin, and use the mixin at the mentioned routes.

Don't `window.scrollTop(0, 0)` in beforeModel or similar hook. This will not preserve scroll position when using browser's back button. #DontBreakTheWeb

### PR DESCRIPTION
**Pull request by sourabh1031**
Fix #418

### CODE REVIEW

**Comment by abhishek97** [comment]
@sourabh1031 This works.
However, we need to preserve scroll position for tabs here 
Screenshot 2019-05-27 at 10 53 57 PM

Try scrolling a bit and then switching tabs. We don't want scroll to top here

**Comment by sourabh1031** [comment]
@abhishek97 all the routes are written in Router.map() in the app/router.js file and you want that only these routes which you showed above in image  should not scroll to top .But the thing is i can't write these routes outside of map function.

**Comment by sourabh1031** [comment]
@abhishek97 i have made the required changes.

**Comment by abhishek97** [comment]
@sourabh1031 This doesn't work. I think you need to specify the `preserveScrollPosition` qp on overview, announcements ..etc child routes rather than on `timeline`. Please run project and test before sending PR

**Pull request closed without merging**
