### PR TITLE
Copyright and rating align

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Resolves issues 3, 7, 9 and 15

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
Introduced copyright symbol, fixed overflowing rating and center aligned col headings in the leaderboard section

**Comment by abhishek97** [comment]
We don't accept CSS change here, you will need to make an appropriate PR in motley for any CSS changes.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 already have, here https://github.com/coding-blocks/motley/pull/217.
Please review

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 Updated PR, please have a look

**Comment by abhishek97** [comment]
@VibhorCodecianGupta Add screenshots please.

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 please review

screen shot 2018-08-12 at 9 26 33 pm

screen shot 2018-08-12 at 9 27 26 pm

**Pull request merged**
