### PR TITLE
Spinner feature

### LINKED ISSUE #350: Show spinner while loading more courses
https://online.codingblocks.com/courses

When user clicks "Load More" button, a spinner should indicate loading state

### PR DESCRIPTION
**Pull request by nileshpatra**
fixes #350 , I have made the changes asked in my previous PR(#408) on the same issue.

### CODE REVIEW

**Comment by abhishek97** [comment]
`app/pods/courses/index/ext_images/spinner.gif` is not where you put static images. all static assets go inside public folder

**Comment by abhishek97** [comment]
We already have a loader component. 
Let's use that

**Comment by nileshpatra** [comment]
@abhishek97 , did the change . Here's a screenshot :  
Screenshot from 2019-05-20 21-09-57

**Comment by nileshpatra** [comment]
@abhishek97 may I know as to why is it closed?😅

**Pull request closed without merging**
