### PR TITLE
div wrapper removed from button

### LINKED ISSUE #413: Remove <div> wrapper from <button>
There are two primitive button class types used in our platform:-
`.button-solid` & `.button-dashed`

In some files, `<button>` elements are wrapped inside `<div>`. Remove the `<div>` wrapper and apply all the classes and actions to `<button>` respectively. 

For instance, you will find in `/app/pods/components/otp-enroll/template.hbs::line22`
```
<div class="button-solid" {{action 'handleClick'}}>
  <button>{{buttonText}}</button>
</div>
```
After refactoring it should look like
`<button class="button-solid" {{action 'handleClick'}}>{{buttonText}}</button>`

### PR DESCRIPTION
**Pull request by farhan787**
fixes #413

### CODE REVIEW

**Comment by farhan787** [comment]
@abhishek97 please review :-)

**Comment by vdvibhu20** [comment]
There are still some places where refactoring is needed.
**One** of those locations is `/app/pods/attempt/content/quiz/attempt/done/template.hbs`.

**Comment by farhan787** [comment]
I thought that they should remain like that but I'm doing it at all places.

**Comment by farhan787** [comment]
> **One** of those locations is `/app/pods/attempt/content/quiz/attempt/done/template.hbs`.

@vdvibhu20 do I also have to change `button-solid` class with actual `button` element for this file that you're telling me ?

**Comment by vdvibhu20** [comment]
> > **One** of those locations is `/app/pods/attempt/content/quiz/attempt/done/template.hbs`.
> 
> @vdvibhu20 do I also have to change `button-solid` class with actual `button` element for this file that you're telling me ?

No in this file remove the `div` wrapper and add the classes to link-to

**Comment by farhan787** [comment]
Ok, got it.

**Comment by farhan787** [comment]
@vdvibhu20 please review it :-)

**Comment by vdvibhu20** [comment]
still some files have div wrapper

**Comment by farhan787** [comment]
> still some files have div wrapper

@vdvibhu20 I thought that those should be inside div wrapper but now I've remove all the div wrappers from buttons. Please review it again :-)

**Comment by vdvibhu20** [comment]
remove conflicts and sync with master.

**Comment by farhan787** [comment]
> remove conflicts and sync with master.

@vdvibhu20 Done

**Comment by vdvibhu20** [comment]
file `app/pods/attempt/content/quiz/attempt/done/template.hbs:` still has div wrapper **and many more**
make it count this time.

**Comment by farhan787** [comment]
@vdvibhu20 if there's a div element having multiple children and button is also one of them then should I remove that div wrapper too from that button ?

**Comment by vdvibhu20** [comment]
> @vdvibhu20 if there's a div element having multiple children and button is also one of them then should I remove that div wrapper too from that button ?

if it is having any of the classes `.button-solid` or `.button-dashed` then yes.

**Comment by farhan787** [comment]
@vdvibhu20 removed remaining div wrappers too and synced with master.

**Comment by farhan787** [comment]
@vdvibhu20 your review please :-)

**Comment by vdvibhu20** [comment]
> @vdvibhu20 your review please :-)

open shell 
type `man git-grep` 
read it 
use it
There is still some files left
and make it count this time :-)

**Pull request closed without merging**
