### PR TITLE
add section id in url params

### PR DESCRIPTION
**Pull request by jatinkatyal13**

### CODE REVIEW

**Comment by abhishek97** [comment]
This pull request **introduces 1 alert** when merging 4d7696cf8f01f07c08e1c1cb3d760154ac8737a0 into 889da135ca231f18419264db96f32ed3eeaa06ab - [view on LGTM.com](https://lgtm.com/projects/g/coding-blocks/codingblocks.online.projectx/rev/pr-e398374e7a4b33addb9c67d4f3db72787df8a4ce)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jatinkatyal13** [comment]
@abhishek97 there is still just one problem

when I reload the page, the left sidebar doesn't scroll to the opened section. I have to scroll to it manually.

**Comment by abhishek97** [comment]
This pull request **introduces 1 alert** when merging 2e7a3956df26020ea95f10996d6cdb5b3683df90 into f81da215f637c427dac45a82648ab77d4d51e5ec - [view on LGTM.com](https://lgtm.com/projects/g/coding-blocks/codingblocks.online.projectx/rev/pr-716c6aaab9d70ab8df70c4cf505d7493810edd8f)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by abhishek97** [comment]
This pull request **introduces 1 alert** when merging 7771059612b296c49532917e790bbf18d721b753 into 52a4ce10bbc175f4dea15ca04f80181e33d950ad - [view on LGTM.com](https://lgtm.com/projects/g/coding-blocks/codingblocks.online.projectx/rev/pr-454f2ae2848e51df35a7a312b8adc9a0d6c33095)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request closed without merging**
