### PR TITLE
Change x from table of contents

### PR DESCRIPTION
**Pull request by Dhroov7**
### Is this PR regarding CSS? 
This project uses motley(https://github.com/coding-blocks/motley/) as css framework. We don't accept css changes here. Please consider a PR to motley instead

### CODE REVIEW

**Comment by abhishek97** [comment]
Screenshots please.

**Comment by Dhroov7** [comment]
screen shot 2018-06-23 at 2 47 00 pm

**Comment by witty123** [comment]
@Dhroov7 show a menu icon instead

**Comment by witty123** [comment]
@Dhroov7 updates ?

**Pull request merged**
