### PR TITLE
Feedback modal

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
motley PR https://github.com/coding-blocks/motley/pull/271

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
screen shot 2018-08-13 at 4 26 21 pm

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 already refactored, please have a look :)

**Comment by VibhorCodecianGupta** [comment]
This is how it looks @abhishek97 

loop

**Comment by VibhorCodecianGupta** [comment]
@witty123 updates?

**Comment by witty123** [comment]
Closing this PR since there's no bounty claim for this PR and the other PR is nearer to completion.

**Pull request closed without merging**
