### PR TITLE
Added SVG Icons

### PR DESCRIPTION
**Pull request by ananay**
Made exactly like the png files!

### CODE REVIEW

**Comment by ananay** [comment]
#90

**Comment by abhishek97** [comment]
Add Screenshots

**Comment by ananay** [comment]
Screenshots

image

image

image

image

image

image

image

image

image

image

image

image

image

image

**Comment by abhishek97** [comment]
@ananay Looks Good!, please make a PR to motley for CSS changes. https://github.com/coding-blocks/motley

**Comment by ananay** [comment]
@abhishek97 Thanks! Do I also need to add the ".svg" files to motley's examples folder or just push the changes in the scss files?

**Comment by abhishek97** [comment]
@ananay Yes add `.svg` to motley too.

**Comment by ananay** [comment]
@abhishek97 https://github.com/coding-blocks/motley/pull/173

**Comment by championswimmer** [comment]
closing in favour of motely pr

**Pull request closed without merging**
