### PR TITLE
Show free trial if course is not premium

### PR DESCRIPTION
**Pull request by Dhroov7**
### Is this PR regarding CSS? 
This project uses motley(https://github.com/coding-blocks/motley/) as css framework. We don't accept css changes here. Please consider a PR to motley instead

### CODE REVIEW

**Comment by Dhroov7** [comment]
screen shot 2018-07-02 at 9 59 53 pm

**Comment by witty123** [comment]
@Dhroov7 this will probably break if the length of content inside the card increases. Can we instead append the phrase "Free trial" in front of the course name itself ?

**Comment by abhishek97** [comment]
@Dhroov7 Yes it'll break the UI. Let's just have "Free Trial" appended to the Run's name.

**Comment by Dhroov7** [comment]
@witty123 @abhishek97 Changed the UI.

**Comment by witty123** [comment]
@Dhroov7 update screenshot as well please, for different screen widths

**Comment by Dhroov7** [comment]
screen shot 2018-07-03 at 4 12 00 pm
screen shot 2018-07-03 at 4 11 42 pm
screen shot 2018-07-03 at 4 11 29 pm

**Comment by Dhroov7** [comment]
@abhishek97 Done.

**Comment by witty123** [comment]
screen shot 2018-07-03 at 6 33 45 pm
Everything is a free trial ?
@Dhroov7 @abhishek97

**Comment by abhishek97** [comment]
@witty123 this is due to data being fetched in the background. We need to work on data requests for this route, which is independent of this PR.

**Comment by witty123** [comment]
Yes but how the user views/understands the website is different than how it is for us. No information is better than wrong information in this case. Maybe show the filter only when the job is complete ?

**Comment by abhishek97** [comment]
@witty123 Totally, the behavior is buggy at best. Reverted this until we fix data loading pattern.

**Pull request merged**
