### PR TITLE
Changes for UX

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
This contains some changes to CSS, if they get approved, will make a PR to Motley as well.

### CODE REVIEW

**Comment by witty123** [comment]
@VibhorCodecianGupta please make the corresponding changes in motley as well.

**Comment by VibhorCodecianGupta** [comment]
gif

**Comment by witty123** [comment]
@VibhorCodecianGupta LGTM.
I only have one issue though, this is getting converted into one really BIG PR and it's going to be a herculean task to review all of the features/fixes. Can we instead have multiple PRs for individual feature/fix ? It would be really awesome if you can do that.

**Comment by VibhorCodecianGupta** [comment]
@witty123 sure! what all features do you want me to make separate PRs for? All of them, or just a few major ones which require quite a bit of change here and there?

**Comment by witty123** [comment]
Just so that the PRs are easy to review. Not all of them. Big feature in
single PR. Grammatical fixes in one. Small bug fixes in another. Things
like that.

**Comment by VibhorCodecianGupta** [comment]
@witty123 I'll open multiple PRs, and I'll refer to the changes made in them by their corresponding numbers here. 
So for example, if a PR is for the first solution mentioned here, I'll just say there that it resolves 1. and so on.

**Comment by VibhorCodecianGupta** [comment]
@witty123 submitting multiple PRs, I'll mention the issues they resolve by their numbers in the parent issue to this PR. So if a PR says that it solves issue 1, then it solves the first issue mentioned in the list in issue #190

**Comment by witty123** [comment]
Closing this PR then.

**Comment by VibhorCodecianGupta** [comment]
#206 #207 #208 #209 #211 #212 

@championswimmer @witty123 @abhishek97 all these PRs (child PRs for this one) were successfully merged. I accidentally made a wrong claim of 300 BOUNTY on this PR, where it should have been 500. It'd be great if you could correct that.

**Pull request closed without merging**
