### PR TITLE
deprecated jquery removed from project

### LINKED ISSUE #419: Deprecate Jquery
Jquery was included by default in Ember.js. Though it has served its purpose well, current state of ember and browsers no longer needs Jquery. Ember also has officially [deprecated Jquery](https://github.com/emberjs/rfcs/blob/master/text/0386-remove-jquery.md), we also wish to do the same.

Task: Remove all usages of jQuery throughout the project. One way to get started is to remove `@ember/jquery` package from package.json and re-rerun `yarn install` and check for errors due to absence of Jquery and fix them with suitable Vanilla JS / Ember code.

### PR DESCRIPTION
**Pull request by farhan787**
fixes #419

### CODE REVIEW

**Comment by abhishek97** [comment]
Please run projects before submitting a PR.

**Comment by farhan787** [comment]
@abhishek97 I ran the project before submitting the PR, it was working fine. Could you please tell me what's going wrong with this ?

**Comment by abhishek97** [comment]
@farhan787 It will not work fine. If you remove 
`import $ from '@ember/jquery'`
any references to `$` will throw error.

**Comment by farhan787** [comment]
@abhishek97 [see this](https://github.com/coding-blocks/hacker-blocks/blob/e7441bb0a9dffbffb5a43c0314777df796bdceb8/app/pods/components/code-editor/component.js#L6) here `$` is used inside Ember modules without import jquery.

**Comment by jatinkatyal13** [comment]
@farhan787 Just running the project won't help check if the components that rely on JQeury are working or not!
Maybe [this](https://shipshape.io/blog/ember-without-jquery/) will help

**Pull request closed without merging**
