### PR TITLE
Added SVG icons

### LINKED ISSUE #90: use svg for course content icons
image

This is 500 points because whoever solves the issues needs to come up with the svgs too :D 
(Use a PNG as a fallback probably)

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
PNG images used as fallback
fixes #90

### CODE REVIEW

**Comment by abhishek97** [comment]
Add screenshots

**Comment by VibhorCodecianGupta** [comment]
Screenshots follow. 

screen shot 2018-06-06 at 4 11 58 pm

screen shot 2018-06-06 at 4 12 42 pm

screen shot 2018-06-06 at 4 13 22 pm

screen shot 2018-06-06 at 4 14 25 pm

screen shot 2018-06-06 at 4 15 42 pm

screen shot 2018-06-06 at 4 16 27 pm

screen shot 2018-06-06 at 4 17 04 pm

screen shot 2018-06-06 at 4 17 52 pm

screen shot 2018-06-06 at 4 19 07 pm

screen shot 2018-06-06 at 12 29 45 pm

**Comment by ananay** [comment]
@VibhorCodecianGupta I tried opening the SVGs but they won't open for some reason. Is there something wrong on my end?

P.S. I'm not a mentor but just wanna know why it doesn't work. I'm using Sketch for Mac.

**Comment by VibhorCodecianGupta** [comment]
Try it on some online editor @ananay ?

**Comment by VibhorCodecianGupta** [comment]
@ananay , I have no idea how Sketch works. I'm assuming that you design a graphic and then export it as an SVG, which automatically generates the code? I could be totally wrong here. I did not have access to my machine, so I made these online, coding the dimensions directly. I guess that's why they wouldn't open at your end. Again, I could be wrong.

**Comment by abhishek97** [comment]
Make a PR on motley instead.

**Comment by VibhorCodecianGupta** [comment]
Just did.

**Pull request closed without merging**
