### PR TITLE
Highlighting current content

### LINKED ISSUE #245: Highlight the current content
The content which is currently being viewed should be highlighted in some manner to provide feedback to the user. 

- The Design and DOM layout (motley PR): 300 Bounty
- Implementation: 200 Bounty

screen_shot_2018-08-12_at_9_52_18_pm

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
fixes #245

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
screen shot 2018-08-13 at 5 47 50 pm

**Comment by VibhorCodecianGupta** [comment]
@abhishek97

**Comment by abhishek97** [comment]
@VibhorCodecianGupta How this is any different from #250 ? 


> Insanity Is Doing the Same Thing Over and Over Again and Expecting Different Results

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 my bad, i had no idea there was already a duplicate submitted. Nevertheless, this was committed before. And I think it works too?

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 I hadn't noticed there was a duplicate to this. Nevertheless, this was committed first

**Pull request closed without merging**
