### PR TITLE
Add: Modal for Player Instructions

### PR DESCRIPTION
**Pull request by firefinchdev**

### CODE REVIEW

**Comment by firefinchdev** [comment]
@championswimmer 
Solves #136 
Pls Review

**Comment by firefinchdev** [comment]
screenshot from 2018-07-22 03-38-16

**Comment by vdvibhu20** [comment]
@firefinchdev  hide modal for mobile

**Comment by firefinchdev** [comment]
Done @vdvibhu20

**Comment by firefinchdev** [comment]
@abhishek97 
Motley changes are merged.

**Comment by abhishek97** [comment]
@firefinchdev can you confirm this? it doesn't seem to work for me; i see no modal, just overlay

**Comment by firefinchdev** [comment]
@abhishek97 
Actually there was a file which I forgot to commit in previous motley PR.
Thus, new motley PR was made. 
https://github.com/coding-blocks/motley/pull/242/
After merging this, Modal works perfectly.

**Pull request merged**
